# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
AWSTemplateFormatVersion: '2010-09-09'
Description:
  An AWS CloudFormation template for bringing up an EC2 instance.
Parameters:
  InstanceType:
    AllowedValues: [
      t1.micro, t2.nano, t2.micro, t2.small, t2.medium, t2.large,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m1.small, m1.medium, m1.large, m1.xlarge, m2.xlarge, m2.2xlarge, m2.4xlarge,
      m3.medium, m3.large, m3.xlarge, m3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      c1.medium, c1.xlarge,
      c3.large, c3.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge,
      c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, g2.2xlarge,
      g2.8xlarge,
      r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge, r3.8xlarge,
      i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge,
      hi1.4xlarge, hs1.8xlarge, cr1.8xlarge, cc2.8xlarge, cg1.4xlarge ]
    Default: t3.nano  # Setting default to the cheapest
    Description: EC2 instance type
    Type: String
  AmiId:
    # For more details on using Systems Manager Public Parameters, see
    # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-about.html#parameter-store-public-parameters
    # For more information about using this public, see
    # https://aws.amazon.com/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-systems-manager-parameter-store/
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Description: Amazon Linux image to use
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
      - /aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-x86_64-ebs
  SSHKeyName:
    Description: The EC2 KeyPair for SSH access to the EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
  IamInstanceProfileArn:
    Type: String
    Description: ARN of the IAM instance profile to attach to the EC2 instance
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::GroupName>
    Description: Security groups to attach to the EC2 instance
  HDSize:
    Type: Number
    Description: EC2 instance root hard drive volume size in GB
    Default: 10
  StartupScriptPath:
    Type: String
    Description: S3 path to a script to execute at startup on the EC2 instance
    Default: s3://s3-bucket/execute-node-script.sh
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref SSHKeyName
        SecurityGroups: !Ref SecurityGroups
        IamInstanceProfile:
          Arn: !Ref IamInstanceProfileArn
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref HDSize
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            sudo yum install -y awscli
            aws s3 ${StartupScriptPath} startupscript
            chmod +x startupscript
            ./startupscript
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
